"""
Brand Database Generator Script

Captures screenshots of known legitimate brand login/home pages
and computes their ResNet-50 visual embeddings for the brand_db.json.

Usage:
    cd ml-service
    python scripts/generate_brand_db.py

Requirements:
    - playwright install chromium
    - All ML dependencies installed (requirements.txt)

Output:
    app/models/brand_db.json — populated with real embeddings
"""

import asyncio
import json
import logging
import sys
from pathlib import Path

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("brand_db_gen")

# Brands to capture + their canonical login/home URLs
BRAND_URLS = {
    "google": "https://accounts.google.com",
    "microsoft": "https://login.microsoftonline.com",
    "apple": "https://appleid.apple.com",
    "paypal": "https://www.paypal.com/signin",
    "amazon": "https://www.amazon.com/ap/signin",
    "facebook": "https://www.facebook.com/login",
    "github": "https://github.com/login",
    "linkedin": "https://www.linkedin.com/login",
    "twitter": "https://twitter.com/login",
    "netflix": "https://www.netflix.com/login",
    "dropbox": "https://www.dropbox.com/login",
}

OUTPUT_PATH = Path(__file__).parent.parent / "app" / "models" / "brand_db.json"
SCREENSHOT_DIR = Path(__file__).parent.parent / "scripts" / "brand_screenshots"


async def capture_brand_screenshots():
    """Capture screenshots of all brand pages."""
    from playwright.async_api import async_playwright

    SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
    captured = {}

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        )

        for brand, url in BRAND_URLS.items():
            logger.info(f"Capturing: {brand} — {url}")
            page = await context.new_page()
            try:
                await page.goto(url, timeout=20000, wait_until="networkidle")
                path = SCREENSHOT_DIR / f"{brand}.png"
                await page.screenshot(path=str(path), type="png")
                captured[brand] = str(path)
                logger.info(f"  ✅ Saved: {path}")
            except Exception as e:
                logger.warning(f"  ❌ Failed to capture {brand}: {e}")
            finally:
                await page.close()

        await browser.close()

    return captured


def compute_embeddings(captured: dict) -> list:
    """Compute ResNet-50 embeddings for all captured brand screenshots."""
    import torch
    import torchvision.models as models
    import torchvision.transforms as transforms
    import numpy as np
    from PIL import Image

    logger.info("Loading ResNet-50...")
    model_base = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
    model = torch.nn.Sequential(*list(model_base.children())[:-1])
    model.eval()

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    entries = []
    for brand, path in captured.items():
        try:
            img = Image.open(path).convert("RGB")
            tensor = transform(img).unsqueeze(0)
            with torch.no_grad():
                emb = model(tensor).squeeze().numpy()
            # L2 normalize
            norm = np.linalg.norm(emb)
            if norm > 0:
                emb = emb / norm
            entries.append({"brand": brand, "embedding": emb.tolist()})
            logger.info(f"  ✅ Embedding computed for {brand} ({len(emb)} dims)")
        except Exception as e:
            logger.error(f"  ❌ Embedding failed for {brand}: {e}")

    return entries


async def main():
    logger.info("=== Brand DB Generator ===")
    logger.info(f"Capturing {len(BRAND_URLS)} brand pages...")

    captured = await capture_brand_screenshots()

    if not captured:
        logger.error("No screenshots captured. Exiting.")
        return

    logger.info(f"\nComputing embeddings for {len(captured)} brands...")
    entries = compute_embeddings(captured)

    db = {
        "_comment": "Auto-generated by scripts/generate_brand_db.py",
        "_version": "1.0.0",
        "_model": "ResNet50 (IMAGENET1K_V2) — 2048-dim L2-normalized embedding",
        "entries": entries,
    }

    with open(OUTPUT_PATH, "w") as f:
        json.dump(db, f, indent=2)

    logger.info(f"\n✅ Brand DB saved: {OUTPUT_PATH}")
    logger.info(f"   Total entries: {len(entries)}")


if __name__ == "__main__":
    asyncio.run(main())
