/**
 * blocklist.js
 *
 * Fast-path L1 phishing blocklist check.
 * Loads a SHA-256 hash-set generated by scripts/sync-blocklist.js and provides
 * an O(1) membership test per scan — no network calls at scan time.
 *
 * Gate position in scan.js: after whitelist, before Redis cache.
 * A blocklist hit short-circuits to MALICIOUS immediately, skipping L2/L3.
 *
 * The hash-set stores SHA-256(url.trim().toLowerCase()), so the same
 * normalisation must be applied at lookup time (see isBlocklisted below).
 *
 * Refresh: run scripts/sync-blocklist.js on a schedule (every 6 h recommended).
 * If the file is missing, the blocklist is a no-op (scan proceeds normally).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const logger = require('../utils/logger');

const BLOCKLIST_PATH = path.resolve(__dirname, '../../config/phishing_blocklist.json');

let blocklistHashes = new Set();
let blocklistLoaded = false;
let lastLoadedAt = null;

// ── Load blocklist ────────────────────────────────────────────────────────────
function loadBlocklist() {
  try {
    const raw = fs.readFileSync(BLOCKLIST_PATH, 'utf-8');
    const data = JSON.parse(raw);
    blocklistHashes = new Set(data.hashes || []);
    blocklistLoaded = true;
    lastLoadedAt = data.updated || null;
    logger.info(`✅ Phishing blocklist loaded: ${blocklistHashes.size} hashes (updated: ${lastLoadedAt})`);
  } catch (err) {
    if (err.code === 'ENOENT') {
      logger.warn('Phishing blocklist not found — run scripts/sync-blocklist.js to generate it. Blocklist gate disabled.');
    } else {
      logger.error(`Failed to load phishing blocklist: ${err.message}`);
    }
    blocklistLoaded = false;
  }
}

// Load on module initialisation
loadBlocklist();

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Tests whether a URL is in the local phishing blocklist.
 * Normalises the URL (trim + lowercase) before hashing, matching the
 * normalisation applied by sync-blocklist.js.
 *
 * @param {string} url - Full URL string
 * @returns {boolean} true if the URL is a known-phishing match
 */
function isBlocklisted(url) {
  if (!blocklistLoaded || !url) return false;
  const hash = crypto.createHash('sha256').update(url.trim().toLowerCase()).digest('hex');
  return blocklistHashes.has(hash);
}

/**
 * Returns metadata about the currently-loaded blocklist.
 * @returns {{ loaded: boolean, size: number, updatedAt: string|null }}
 */
function getBlocklistInfo() {
  return {
    loaded: blocklistLoaded,
    size: blocklistHashes.size,
    updatedAt: lastLoadedAt,
  };
}

module.exports = { isBlocklisted, loadBlocklist, getBlocklistInfo };
